CREATE DATABASE flashcardsdb;

CREATE TABLE IF NOT EXISTS users(
    id SERIAL PRIMARY KEY,
    username TEXT UNIQUE NOT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    pwdHash VARCHAR(255) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS decks(
    id SERIAL PRIMARY KEY,
    title TEXT NOT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    public BOOLEAN DEFAULT TRUE,
    userId INTEGER NOT NULL,
    FOREIGN KEY(userId) REFERENCES users(id),
    UNIQUE (userId, title)
);

CREATE TABLE IF NOT EXISTS flashcards(
    id SERIAL PRIMARY KEY,
    front TEXT NOT NULL,
    back TEXT NOT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    deckId INTEGER NOT NULL,
    FOREIGN KEY(deckId) REFERENCES decks(id),
    UNIQUE (front, deckId)
);
